defaults:
  - _self_
  - model: ripplenerf 

learning:
  learning_rate: 0.001
  batch_size: 128
  weight_decay: 0.00000001
  beta_ema: 0.9999
  gradient_clip: 0.1
  max_epochs: 100
  use_wandb: false
  wandb_project_name: ""
  use_amp: false
  save_folder: saved/
  val_split: 0.01
  num_epochs: 100
  num_workers: 4
  num_devices: 2

  scheduler_interval: "epoch"
  loss_monitor: "validation_total_loss"
  scheduler_frequency: 1

rendering_train:
  near_plane_distance: 2.0
  far_plane_distance: 6.0
  num_bins: 192

rendering_eval:
  near_plane_distance: 2.0
  far_plane_distance: 6.0
  num_bins: 192

data:
  data_path: "data/truck_data/"

lr_scheduler:
  type: ReduceLROnPlateau
  patience: 50
  factor: 0.1
  
model_name: "nerf"