defaults:
  - _self_

learning:
  learning_rate: 0.001
  batch_size: 32
  weight_decay: 0.0001
  beta_ema: 0.9999
  gradient_clip: 0.1
  max_epochs: 100
  use_wandb: false
  wandb_project_name: ""
  use_amp: false
  save_folder: saved/
  val_split: 0.01
  num_epochs: 100
  num_workers: 4
  num_gpus: 1

  scheduler_interval: "epoch"
  loss_monitor: "validation total loss"
  scheduler_frequency: 1

rendering:
  near_plane_distance: 0.0
  far_plane_distance: 1.0
  num_bins: 192

model:
  input_dim: 5
  hidden_dim: 128
  embedding_dim_pos: 10
  embedding_dim_direction: 4

lr_scheduler:
  type: ReduceLROnPlateau
  patience: 50
  factor: 0.1
  
model_name: "nerf"